# Generated by Django 3.2.6 on 2021-09-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, default='pictures/no-img.jpg', null=True, upload_to='pictures'),
        ),
    ]
