# Generated by Django 3.2.6 on 2021-10-08 08:21

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20211008_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, default='/media/no-img.jpg', null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/pictures'), upload_to=''),
        ),
    ]
