# Generated by Django 3.2.6 on 2021-10-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_ticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, default='pictures/no-img.jpg', null=True, upload_to='pictures'),
        ),
    ]
