# Generated by Django 3.2.6 on 2021-10-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20211008_1709'),
        ('reviews', '0005_alter_ticket_image'),
    ]

    operations = [
    ]
