# Generated by Django 3.2.6 on 2021-10-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_alter_ticket_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating_empty_star',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='rating_full_star',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
